server:
  port: 8080
  shutdown: graceful
#  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:keystore/sbip.p12
#    key-store-password: p@ssw0rd
#    key-alias: sbip

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/master
  jpa:
    hibernate:
      ddl-auto: none
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:sql/schema.sql
#      data-locations: classpath:sql/data.sql
  datasource:
    initialization-mode: always
    hikari:
      maximum-pool-size: 10
    url: jdbc:h2:mem:sbipdb
    driver-class-name: org.h2.Driver
    username: root
    password: root
    h2:
      console:
        enabled: true
  lifecycle:
    timeout-per-shutdown-phase: 1m

app:
  description: Spring boot course
  version: V1
  sbip:
    ct:
      name: Rastreador de cursos
      ip: 127.0.0.1
      port: 9090
      security:
        enabled: true
        token: 038837hfjh89iohfiodhfdl
        roles: USER,ADMIN
  timeout: ${APP_TIMEOUT:0}

management:
  #server:
  #  port: 8081
  endpoint:
    health:
      status:
        http-mapping:
          down: 500
          out_of_service: 503
        order:
          - FATAL
          - DOWN
          - OUT-OF-SERVICE
          - UNKNOWN
          - UP
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
        #include:
        #  - releaseNotes

  info:
    env:
      enabled: true

info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@
    properties.java.version: @java.version@
  app:
    name: Aplicativo de estudo
    description: aplicativo feito para explorar os recursos do spring boot
    version: 1.0

#logging:
#  file:
#    console: clr(%d{dd-MM-yyyy HH:mm:ss.SSS}){yellow}%clr(${PID:- }){verde} %magenta([%thread]) %highlight([%-5level])%clr(%-40.40logger{39}){cyan} %msg%n
#    name: application.log
#  logback:
#    rollingpolicy:
#      max-file-size: 1MB
#      max-history: 1