server:
  port: 8080
  shutdown: graceful

spring:
  jpa:
    hibernate:
      ddl-auto: none
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:sql/schema.sql
#      data-locations: classpath:sql/data.sql
  datasource:
    initialization-mode: always
    hikari:
      maximum-pool-size: 10
    url: jdbc:h2:mem:sbipdb
    driver-class-name: org.h2.Driver
    username: root
    password: root
    h2:
      console:
        enabled: true
  lifecycle:
    timeout-per-shutdown-phase: 1m

app:
  sbip:
    ct:
      name: Rastreador de cursos
      ip: 127.0.0.1
      port: 9090
      security:
        enabled: true
        token: 038837hfjh89iohfiodhfdl
        roles: USER,ADMIN
  timeout: ${APP_TIMEOUT:0}

#logging:
#  file:
#    console: clr(%d{dd-MM-yyyy HH:mm:ss.SSS}){yellow}%clr(${PID:- }){verde} %magenta([%thread]) %highlight([%-5level])%clr(%-40.40logger{39}){cyan} %msg%n
#    name: application.log
#  logback:
#    rollingpolicy:
#      max-file-size: 1MB
#      max-history: 1