INSERT INTO AUTHORS(ID, NAME, BIO)  VALUES(1, 'John Doe', 'Author of several Spring Boot courses');
INSERT INTO AUTHORS(ID, NAME, BIO)  VALUES(2, 'Steve Muller', 'Author of several popular Spring and Python courses');
INSERT INTO AUTHORS_COURSES(AUTHOR_ID, COURSE_ID) VALUES(1, 100);
INSERT INTO AUTHORS_COURSES(AUTHOR_ID, COURSE_ID) VALUES(1, 200);
INSERT INTO AUTHORS_COURSES(AUTHOR_ID, COURSE_ID) VALUES(2, 100);
INSERT INTO AUTHORS_COURSES(AUTHOR_ID, COURSE_ID) VALUES(2, 200);
INSERT INTO AUTHORS_COURSES(AUTHOR_ID, COURSE_ID) VALUES(2, 300);