apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: course-tracker
  name: course-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-tracker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: course-tracker
    spec:
      containers:
      - image: fabricio211/course-tracker
        name: course-tracker
        resources: {}
status: {}
