apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: course-tracker
  name: course-tracker
spec:
  type: ClusterIP
  ports:
  - name: 80-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: course-tracker
status:
  loadBalancer: {}
